service: mochi-test-back-end-solution
frameworkVersion: '2'
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  memorySize: 256
  tracing:
    lambda: true
    apiGateway: true
  environment:
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:BatchGetItem
        - dynamodb:ConditionCheckItem
        - dynamodb:DescribeContributorInsights
        - dynamodb:Scan
        - dynamodb:ListTagsOfResource
        - dynamodb:Query
        - dynamodb:DescribeStream
        - dynamodb:DescribeTimeToLive
        - dynamodb:ListStreams
        - dynamodb:DescribeGlobalTableSettings
        - dynamodb:DescribeReservedCapacityOfferings
        - dynamodb:PartiQLSelect
        - dynamodb:DescribeTable
        - dynamodb:GetShardIterator
        - dynamodb:DescribeGlobalTable
        - dynamodb:DescribeReservedCapacity
        - dynamodb:GetItem
        - dynamodb:DescribeContinuousBackups
        - dynamodb:DescribeExport
        - dynamodb:DescribeKinesisStreamingDestination
        - dynamodb:DescribeBackup
        - dynamodb:DescribeLimits
        - dynamodb:GetRecords
        - dynamodb:DescribeTableReplicaAutoScalin
      Resource: 
        - arn:aws:dynamodb:us-east-1:248546885109:table/users
        - arn:aws:dynamodb:*:*:table/users
        - arn:aws:logs:us-east-1:248546885109:log-group:/aws/lambda/mochi-test-back-end-solution-dev*:*
        - arn:aws:dynamodb:us-east-1:248546885109:table/users
        - arn:aws:dynamodb:*:*:table/users
      
functions: 
  createUser:
    handler: built/functions/user/index.createUser
    events: 
      - http:
          path: createUser
          method: POST
  uploadPdf:
    handler: built/functions/pdf/index.uploadPdf
    events: 
      - http:
          path: uploadPdf
          method: POST
    environment:
      BUCKET_NAME: mochi-pdfs
  sendEmail:
    handler: built/functions/email/index.reSendEamil
    events: 
      - http:
          path: sendEmail
          method: POST